$engine: 3
$onesync: on
name: FiveM esx Nagisa
author: Nagisa_lpx
description: This is the custom esx template from Nagisa_lpx!(with code from https://github.com/esx-framework/esx-recipes/blob/legacy/recipe.yaml)

tasks:
  # Download default CFX resources

  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[LOCKED]/[cfx-default]

  - action: remove_path
    path: ./resources/[LOCKED]/[cfx-dafault]/[gameplay]/chat-theme-gtao

  # Download and prepare server.cfg / loadingscreen / database

  - action: download_github
    src: https://github.com/Nagisalpx/FiveM-Template-custom-Nagisa_lpx
    ref: main
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/[SERVER]/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/[SERVER]/Benes-OMA.png
    dest: ./Benes-OMA.png

  # Download basic resources and ESX dependencies

  - action: connect_database

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./tmp/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    ref: main
    dest: ./tmp/addons/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    ref: main
    dest: ./tmp/addons/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    ref: main
    dest: ./tmp/addons/esx_datastore

  - action: download_github
    src: https://github.com/esx-framework/esx_policejob
    ref: main
    dest: ./tmp/addons/esx_policejob

  - action: download_github
    src: https://github.com/esx-framework/esx_service
    ref: main
    dest: ./tmp/addons/esx_service

  - action: download_github
    src: https://github.com/esx-framework/esx_rpchat
    ref: main
    dest: ./tmp/addons/esx_rpchat

  - action: download_github
    src: https://github.com/esx-framework/esx_cruisecontrol
    ref: main
    dest: ./tmp/addons/esx_cruisecontrol

  - action: download_github
    src: https://github.com/esx-framework/esx_basicneeds
    ref: main
    dest: ./tmp/addons/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-framework/esx_clotheshop
    ref: main
    dest: ./tmp/addons/esx_clotheshop

  - action: download_github
    src: https://github.com/esx-framework/esx_optionalneeds
    ref: main
    dest: ./tmp/addons/esx_optionalneeds

  - action: waste_time # prevent github throttling
    seconds: 5

  - action: download_github
    src: https://github.com/esx-framework/esx_property
    ref: main
    dest: ./tmp/addons/esx_property

  - action: download_github
    src: https://github.com/esx-framework/esx_dmvschool
    ref: main
    dest: ./tmp/addons/esx_dmvschool

  - action: download_github
    src: https://github.com/esx-framework/esx_barbershop
    ref: main
    dest: ./tmp/addons/esx_barbershop

  - action: download_github
    src: https://github.com/esx-framework/esx_weaponshop
    ref: main
    dest: ./tmp/addons/esx_weaponshop

  - action: download_github
    src: https://github.com/esx-framework/esx_shops
    ref: main
    dest: ./tmp/addons/esx_shops

  - action: download_github
    src: https://github.com/esx-framework/esx_taxijob
    ref: main
    dest: ./tmp/addons/esx_taxijob

  - action: download_github
    src: https://github.com/esx-framework/esx_billing
    ref: main
    dest: ./tmp/addons/esx_billing

  - action: download_github
    src: https://github.com/esx-framework/esx_drugs
    ref: main
    dest: ./tmp/addons/esx_drugs

  - action: download_github
    src: https://github.com/esx-framework/esx_garage
    ref: main
    dest: ./tmp/addons/esx_garage

  - action: download_github
    src: https://github.com/esx-framework/esx_vehicleshop
    ref: main
    dest: ./tmp/addons/esx_vehicleshop

  - action: download_github
    src: https://github.com/esx-framework/esx_joblisting
    ref: main
    dest: ./tmp/addons/esx_joblisting

  - action: download_github
    src: https://github.com/esx-framework/esx_banking
    ref: main
    dest: ./tmp/addons/esx_banking

  - action: download_github
    src: https://github.com/esx-framework/esx_lscustom
    ref: main
    dest: ./tmp/addons/esx_lscustom

  - action: download_github
    src: https://github.com/esx-framework/esx_society
    ref: main
    dest: ./tmp/addons/esx_society

  - action: waste_time # prevent github throttling
    seconds: 5

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    ref: main
    dest: ./tmp/addons/esx_license

  - action: download_github
    src: https://github.com/esx-framework/esx_accessories
    ref: main
    dest: ./tmp/addons/esx_accessories

  - action: download_github
    src: https://github.com/esx-framework/esx_jobs
    ref: main
    dest: ./tmp/addons/esx_jobs

  - action: download_github
    src: https://github.com/esx-framework/esx_ambulancejob
    ref: main
    dest: ./tmp/addons/esx_ambulancejob

  - action: download_github
    src: https://github.com/esx-framework/esx_mechanicjob
    ref: main
    dest: ./tmp/addons/esx_mechanicjob

  - action: download_github
    src: https://github.com/esx-framework/esx_animations
    ref: main
    dest: ./tmp/addons/esx_animations

  - action: download_github
    src: https://github.com/esx-framework/esx_boat
    ref: main
    dest: ./tmp/addons/esx_boat

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    ref: main
    dest: ./tmp/addons/esx_status
    
  - action: download_github
    src: https://github.com/esx-framework/esx_sit
    ref: main
    dest: ./tmp/addons/esx_sit

  - action: move_path
    src: ./tmp/addons/
    dest: ./resources/[esx_addons]

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[LOCKED]/[core]

  - action: move_path
    src: ./tmp/recipe/[RESSOURCES]/[PLUGINS]
    dest: ./resources

  - action: move_path
    src: ./tmp/recipe/[RESSOURCES]/[MAP]
    dest: ./resources

  - action: move_path
    src: ./tmp/recipe/[RESSOURCES]/[CARS]
    dest: ./resources
  - action: remove_path
    path: ./resources/[CARS]/dummy.txt
    
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[LOCKED]/[standalone]/pma-voice

  ## DATABASE

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql

  - action: query_database
    file: ./tmp/recipe/[SQL]/sql.sql

  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/files/oxmysql.zip
  - action: unzip
    src: ./tmp/files/oxmysql.zip
    dest: ./resources/[LOCKED]/[standalone]
    
  ## Cleanup
  - action: remove_path
    path: ./tmp
